# android/gradle.properties
# Performance Gradle
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# React Native
android.useAndroidX=true
android.enableJetifier=true

# Hermes
hermesEnabled=true

# Nouvelle architecture (désactivée par défaut)
newArchEnabled=false
