# android/gradle.properties
# Performance Gradle
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# React Native
android.useAndroidX=true
android.enableJetifier=true

# Hermes
hermesEnabled=true

# Nouvelle architecture (désactivée par défaut)
newArchEnabled=false
